version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c './wait-for db:3306 -- java -jar app.jar'
    ports:
      - 8081:8080
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: springboot_demo
      MYSQL_ROOT_PASSWORD: password